"""
=============================================================
email_alert/send_alert.py
=============================================================
Sends email alerts via Gmail SMTP when an anomaly is detected.

SETUP:
  1. Enable "App Passwords" in your Google account:
     https://myaccount.google.com/apppasswords
  2. Fill in SENDER_EMAIL and APP_PASSWORD below
  3. Set RECEIVER_EMAIL to where you want alerts sent

NOTE: Never commit real credentials to version control.
      Use environment variables in production.
=============================================================
"""

import smtplib
import os
import queue
import threading
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import time

# --------------------------------------------------------
# Email Configuration
# --------------------------------------------------------
SENDER_EMAIL   = os.environ.get("IDS_SENDER_EMAIL", "kallimarsnehil@gmail.com")
APP_PASSWORD   = os.environ.get("IDS_EMAIL_PASSWORD", "ifed vwis pbpr dyht")
RECEIVER_EMAIL = os.environ.get("IDS_RECEIVER_EMAIL", "23d10.snehil@sjec.ac.in")

# --------------------------------------------------------
# Throttle: HIGH = 1 per 10s, MEDIUM/LOW = 1 per 60s
# --------------------------------------------------------
THROTTLE_SECONDS_NON_HIGH = 60
THROTTLE_SECONDS_HIGH     = 10
_last_sent_non_high = 0.0
_last_sent_high     = 0.0
_throttle_lock      = threading.Lock()

# --------------------------------------------------------
# Persistent SMTP mailer — one thread, one connection
# --------------------------------------------------------
_mail_queue   = queue.Queue()
_smtp_conn    = None
_smtp_lock    = threading.Lock()

def _get_smtp():
    """Return a live SMTP connection, reconnecting if needed."""
    global _smtp_conn
    try:
        if _smtp_conn is not None:
            _smtp_conn.noop()   # ping to check if still alive
            return _smtp_conn
    except Exception:
        _smtp_conn = None

    conn = smtplib.SMTP("smtp.gmail.com", 587, timeout=10)
    conn.ehlo()
    conn.starttls()
    conn.login(SENDER_EMAIL, APP_PASSWORD)
    _smtp_conn = conn
    return _smtp_conn


def _mailer_worker():
    """Dedicated background thread that drains _mail_queue and sends emails."""
    while True:
        msg_obj, recipient, label = _mail_queue.get()  # blocks until item available
        try:
            with _smtp_lock:
                server = _get_smtp()
                server.sendmail(SENDER_EMAIL, recipient, msg_obj.as_string())
            print(f"[EMAIL] SUCCESS: Sent alert to {recipient} ({label})")
        except Exception as e:
            print(f"[EMAIL ERROR] Failed to send: {e}")
            # Force reconnect next time
            global _smtp_conn
            _smtp_conn = None
        finally:
            _mail_queue.task_done()


# Start the mailer thread once at import time (daemon so it exits with the process)
_mailer_thread = threading.Thread(target=_mailer_worker, daemon=True)
_mailer_thread.start()


# --------------------------------------------------------
# Build email body
# --------------------------------------------------------
def build_email_body(alert: dict) -> str:
    """Format the alert dictionary into a readable email body."""
    return f"""
🚨 IDS ANOMALY ALERT 🚨
{"=" * 50}

Timestamp  : {alert.get("timestamp", "N/A")}
Severity   : {alert.get("severity", "UNKNOWN")}
Alert Type : {alert.get("type", "N/A")}

Source IP  : {alert.get("src_ip", "N/A")}
Dest IP    : {alert.get("dst_ip", "N/A")}
Protocol   : {alert.get("protocol", "N/A")}

Packet Size  : {alert.get("packet_size", 0)} bytes
Packet Rate  : {alert.get("packet_rate", 0)} packets/sec
ML Confidence: {alert.get("confidence", 0)}%

Message:
  {alert.get("message", "No details available.")}

{"=" * 50}
This alert was generated by the Academic IDS Project.
Do not reply to this email.
"""


# --------------------------------------------------------
# Send email alert
# --------------------------------------------------------
def send_email_alert(alert: dict):
    """
    Enqueues an email notification for a detected anomaly.
    Actual sending is handled by the persistent _mailer_worker thread.
    HIGH severity: sends every 10s max. MEDIUM/LOW: 1 per 60s.
    """
    global _last_sent_non_high, _last_sent_high
    severity = alert.get("severity", "UNKNOWN")
    src_ip   = alert.get("src_ip", "unknown")
    now      = datetime.now().timestamp()

    # Throttle check
    if severity == "HIGH":
        with _throttle_lock:
            if (now - _last_sent_high) < THROTTLE_SECONDS_HIGH:
                return
            _last_sent_high = now
    else:
        with _throttle_lock:
            if (now - _last_sent_non_high) < THROTTLE_SECONDS_NON_HIGH:
                return
            _last_sent_non_high = now

    if "your_gmail" in SENDER_EMAIL or "your_app_password" in APP_PASSWORD:
        print("[EMAIL] Not configured — skipping.")
        return

    # Build the message object
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[IDS ALERT] {severity} — {alert.get('type','?')} from {src_ip}"
    msg["From"]    = SENDER_EMAIL
    msg["To"]      = RECEIVER_EMAIL
    msg.attach(MIMEText(build_email_body(alert), "plain", "utf-8"))

    label = f"{severity}/{alert.get('type','?')}"
    _mail_queue.put((msg, RECEIVER_EMAIL, label))  # non-blocking enqueue
    print(f"[EMAIL] Queued alert for {src_ip} ({label})")


# --------------------------------------------------------
# Test function
# --------------------------------------------------------
def test_email():
    """Send a test alert email to verify configuration."""
    test_alert = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "type": "TEST_ALERT",
        "severity": "LOW",
        "src_ip": "192.168.1.100",
        "dst_ip": "192.168.1.1",
        "protocol": "ICMP",
        "packet_size": 1500,
        "packet_rate": 250.0,
        "confidence": 91.5,
        "message": "This is a test alert from the IDS system."
    }
    send_email_alert(test_alert)


if __name__ == "__main__":
    print("[TEST] Sending test email alert...")
    test_email()
